# 4.2 Universal Functions: Fast Element-Wise Array Functions（通用函数：快速数组函数）


In [1]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.74141285,  0.70082745, -0.63825591, -0.3624283 , -0.10435984,
       -1.19764893, -1.31469993,  1.80832028])

In [5]:
y

array([ 0.45609481, -1.83646239, -1.02167476,  1.95666533,  0.55587418,
        0.85788237, -0.14754355, -0.47751321])

In [6]:
np.maximum(x, y)

array([ 0.74141285,  0.70082745, -0.63825591,  1.95666533,  0.55587418,
        0.85788237, -0.14754355,  1.80832028])

In [7]:
arr = np.random.randn(7) * 5
arr

array([ 1.28456957,  9.22401157, -3.78978489,  1.46254506, -4.72935275,
       -5.14778288, -7.58633147])

In [8]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.28456957,  0.22401157, -0.78978489,  0.46254506, -0.72935275,
       -0.14778288, -0.58633147])

In [9]:
whole_part

array([ 1.,  9., -3.,  1., -4., -5., -7.])

ufunc能接受一个可选参数作为输出，这样可以直接更改原有的数组：

In [10]:
arr

array([ 1.28456957,  9.22401157, -3.78978489,  1.46254506, -4.72935275,
       -5.14778288, -7.58633147])

In [11]:
np.sqrt(arr) # 没有改变原有的arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.13338854, 3.03710579,        nan, 1.20935729,        nan,
              nan,        nan])

In [12]:
np.sqrt(arr, arr) # 改变了原有的arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.13338854, 3.03710579,        nan, 1.20935729,        nan,
              nan,        nan])

In [13]:
arr

array([1.13338854, 3.03710579,        nan, 1.20935729,        nan,
              nan,        nan])